#!/bin/bash

if [ $# -eq 0 ] || [ $1 == "-help"  ]; then
  echo "$./process_Download [RunNum]"
  echo "    RunNum = run number"
  echo "   * if RunNum = all, sync all"
  exit 1
fi;

source ./process_PathSetting

RUN=$1

if [ ${RUN} == "all" ]; then

        #============ Get the raw data
        IP=lab-lan3.onenet
        rsync -avuht --progress "dgs@${IP}:${dataloc}/${expName}_run_*" ${DATADIR}/.
        rsync -avuht --progress "dgs@${IP}:${dataloc}/RunTimeStamp.dat" ${DATADIR}
        scp  "dgs@${IP}:${dataloc}/RunTimeStamp.dat" ${DATADIR}"/RunTimeStamp.txt"
        rsync -avuht --progress "dgs@${IP}:${daqDir}/expName.sh" ${AnalysisDir}/.

        echo "============================================="
        tail -10 ${AnalysisDir}/data/RunTimeStamp.dat
        echo "============================================="
    
    exit 1
fi

#just in case people put %03d as RUN
if [ "${RUN:0:2}" == "00" ]; then
    RUN=${RUN:2:1}
elif [ "${RUN:0:1}" == "0" ]; then
    RUN=${RUN:1:2}
else
    RUN=$(printf '%d' $RUN)
fi


RUN=$(printf '%03d' ${RUN})

echo "PC Name :" $PCName "|" ${PCName:0:5}"|" 


#######################################
####################  Download raw data
echo -e "${RED}######################### Download raw data: run ${RUN}${NC}"
#============ Get the raw data
IP=lab-lan3.onenet

rsync -avuht --progress "dgs@${IP}:${dataloc}/${expName}_run_$RUN.gtd*" ${DATADIR}/.
rsync -avuht --progress "dgs@${IP}:${dataloc}/RunTimeStamp.dat" ${DATADIR}
#cp  ${DATADIR}/"RunTimeStamp.dat" ${DATADIR}"/RunTimeStamp.txt"
rsync -avuht --progress "dgs@${IP}:${daqDir}/expName.sh" ${AnalysisDir}/../.


echo "============================================="
tail -10 ${AnalysisDir}/data/RunTimeStamp.dat
echo "============================================="

echo -e "${YELLOW}"
du -hsc $DATADIR/${expName}_run_$RUN*

count=`ls -1 ${DATADIR}/${expName}_run_$RUN* 2>/dev/null | wc -l`
echo -e "========== Number of Files : ${count}${NC}"
if [ ${count} -eq 0 ]; then
    echo "============================================"
    echo "====  RAW Files of RUN-${RUN} not found! "
    echo "============================================"
    exit 1
fi
